#!/usr/bin/env python3
"""Direct search over apodization window shapes, scored by real encoded bytes.

The encoder is the fitness function: a candidate shape is written as a knot
file, passed to `-w custom:<file>`, and judged by how many bytes the corpus
compresses to. No gradients and no model of the objective are needed — the
encoder is fast, and because it is deterministic the objective is *exact*.
Two evaluations of the same shape return the same integer, so there is no
averaging, no noise floor, and a difference of one byte is a real difference.

    # marginal value of a learned 5th window next to the default four
    bench/window_search.py --train bench/fixtures/music_3s.flac \
                           --validate bench/fixtures/master_1s_mix.flac

    # what a single window can do alone, seeded from tukey(0.5)
    bench/window_search.py --objective standalone --seed tukey050 ...

Two things this script is arranged to keep honest:

*   **Marginal, not standalone, by default.** A window earns its place by what
    it adds to the set already there, so the default objective offers the
    candidate *alongside* the baseline windows and measures the difference.
    Scoring a shape on its own rewards rediscovering tukey(0.5).
*   **Train and validate are separate corpora.** Window shapes have enough
    freedom to fit one excerpt's quirks. Only the validate number, on audio
    the search never saw, means anything; the script always reports both and
    says so when they disagree.

Two optimisers. CMA-ES (`pip install cma`) is the better fit — the space is
multimodal and a covariance model learns which knots matter together — and is
used when importable. The fallback is a hand-rolled Nelder-Mead, so the script
runs with nothing but the standard library. Both are seeded deterministically:
re-running the same command reproduces the same search.
"""

import argparse
import math
import os
import shutil
import subprocess
import sys
import tempfile

# ----------------------------------------------------------------------------
# Window shapes for seeding, as continuous functions of x in [0, 1]
# ----------------------------------------------------------------------------
# These mirror the encoder's formulas closely enough to start a search from a
# known-good shape. They are not used for scoring — the encoder's own
# compiled-in windows are, via --baseline.

def _tukey(x, p):
    if p <= 0.0:
        return 1.0
    if x < p / 2.0:
        return 0.5 * (1.0 + math.cos(math.pi * (2.0 * x / p - 1.0)))
    if x > 1.0 - p / 2.0:
        return 0.5 * (1.0 + math.cos(math.pi * (2.0 * (x - 1.0) / p + 1.0)))
    return 1.0


SEED_SHAPES = {
    "rect":     lambda x: 1.0,
    "hann":     lambda x: 0.5 - 0.5 * math.cos(2.0 * math.pi * x),
    "welch":    lambda x: 1.0 - (2.0 * x - 1.0) ** 2,
    "bartlett": lambda x: 1.0 - abs(2.0 * x - 1.0),
    "tukey005": lambda x: _tukey(x, 0.05),
    "tukey020": lambda x: _tukey(x, 0.20),
    "tukey050": lambda x: _tukey(x, 0.50),
    "tukey075": lambda x: _tukey(x, 0.75),
}


def seed_knots(name, k):
    """Sample a named seed shape at `k` evenly spaced knots."""
    if name not in SEED_SHAPES:
        raise SystemExit("unknown seed '%s' (have: %s)"
                         % (name, ", ".join(sorted(SEED_SHAPES))))
    f = SEED_SHAPES[name]
    return [f(j / (k - 1.0)) for j in range(k)]


# ----------------------------------------------------------------------------
# Candidate -> knot file
# ----------------------------------------------------------------------------

def write_knots(knots, path, lo, hi):
    """Clamp, normalise to peak 1, and write a knot file the encoder can read.

    Normalising is cosmetic rather than corrective: the LPC search is
    scale-invariant, so peak height is a flat direction of the objective. It
    keeps saved shapes comparable by eye and keeps the search from wandering
    off into huge or tiny values that mean nothing.
    """
    v = [min(hi, max(lo, x)) for x in knots]
    peak = max(abs(x) for x in v)
    if peak <= 0.0:
        return False                      # degenerate: encoder rejects it too
    v = [x / peak for x in v]
    with open(path, "w") as fh:
        fh.write("# generated by bench/window_search.py\n")
        for x in v:
            fh.write("%.17g\n" % x)
    return True


# ----------------------------------------------------------------------------
# Fitness: total encoded bytes over a corpus
# ----------------------------------------------------------------------------

class Encoder:
    """Runs the encoder and totals output bytes over a corpus."""

    def __init__(self, binary, mode_flags, verbose=False):
        self.binary = binary
        self.mode = mode_flags
        self.verbose = verbose
        self.runs = 0

    def size(self, corpus, windows, tmpdir):
        """Total encoded bytes for `corpus` with the given -w list."""
        total = 0
        out = os.path.join(tmpdir, "out.flac")
        for src in corpus:
            # -n: no metadata, so only the audio (plus a fixed STREAMINFO) is
            #     weighed, and files stay comparable without metaflac.
            # -R: no frame reuse. Reuse can splice the *input's* frames into
            #     the output, which would mask exactly the search differences
            #     this is trying to measure.
            cmd = ([self.binary, "-q", "-n", "-R"] + self.mode
                   + ["-w", ",".join(windows), src, out])
            r = subprocess.run(cmd, capture_output=True, text=True)
            if r.returncode != 0:
                raise SystemExit("encoder failed on %s:\n%s" % (src, r.stderr.strip()))
            total += os.path.getsize(out)
            self.runs += 1
        return total


class Objective:
    """Maps a knot vector to total encoded bytes, with a memo of past calls.

    The memo is exact rather than approximate: identical knots give identical
    bytes, so a repeat lookup is free information, and Nelder-Mead revisits
    points often (every shrink re-tests the best vertex).
    """

    def __init__(self, enc, train, baseline, marginal, lo, hi, tmpdir):
        self.enc = enc
        self.train = train
        self.baseline = baseline
        self.marginal = marginal
        self.lo, self.hi = lo, hi
        self.tmpdir = tmpdir
        self.cache = {}
        self.best = None            # (bytes, knots)
        self.history = []           # (eval_index, bytes) for improvements only

    def windows_for(self, knot_path):
        cand = "custom:" + knot_path
        return (self.baseline + [cand]) if self.marginal else [cand]

    def __call__(self, knots):
        key = tuple(round(x, 9) for x in knots)
        if key in self.cache:
            return self.cache[key]

        path = os.path.join(self.tmpdir, "cand.txt")
        if not write_knots(knots, path, self.lo, self.hi):
            self.cache[key] = math.inf          # degenerate shape
            return math.inf

        val = self.enc.size(self.train, self.windows_for(path), self.tmpdir)
        self.cache[key] = val
        if self.best is None or val < self.best[0]:
            self.best = (val, list(knots))
            self.history.append((self.enc.runs, val))
            shutil.copy(path, os.path.join(self.tmpdir, "best.txt"))
        return val


# ----------------------------------------------------------------------------
# Nelder-Mead
# ----------------------------------------------------------------------------

def nelder_mead(f, x0, step, max_evals, tol, log=None):
    """Standard Nelder-Mead simplex search. Returns (best_x, best_f).

    Plain textbook coefficients (reflect 1, expand 2, contract 0.5, shrink
    0.5). The objective is integer-valued, so exact ties between vertices are
    common; ordering is stable, which keeps the search from cycling on them.
    """
    n = len(x0)
    simplex = [list(x0)]
    for i in range(n):
        v = list(x0)
        v[i] += step
        simplex.append(v)

    fv = [f(v) for v in simplex]
    evals = len(simplex)

    while evals < max_evals:
        order = sorted(range(len(simplex)), key=lambda i: fv[i])
        simplex = [simplex[i] for i in order]
        fv = [fv[i] for i in order]

        spread = max(max(abs(simplex[i][j] - simplex[0][j]) for j in range(n))
                     for i in range(1, len(simplex)))
        if spread < tol:
            if log:
                log("  converged: simplex spread %.2e < %.2e" % (spread, tol))
            break

        centroid = [sum(v[j] for v in simplex[:-1]) / n for j in range(n)]
        worst = simplex[-1]

        xr = [centroid[j] + (centroid[j] - worst[j]) for j in range(n)]
        fr = f(xr); evals += 1

        if fr < fv[0]:
            xe = [centroid[j] + 2.0 * (centroid[j] - worst[j]) for j in range(n)]
            fe = f(xe); evals += 1
            simplex[-1], fv[-1] = (xe, fe) if fe < fr else (xr, fr)
        elif fr < fv[-2]:
            simplex[-1], fv[-1] = xr, fr
        else:
            xc = [centroid[j] + 0.5 * (worst[j] - centroid[j]) for j in range(n)]
            fc = f(xc); evals += 1
            if fc < fv[-1]:
                simplex[-1], fv[-1] = xc, fc
            else:
                for i in range(1, len(simplex)):
                    simplex[i] = [simplex[0][j] + 0.5 * (simplex[i][j] - simplex[0][j])
                                  for j in range(n)]
                    fv[i] = f(simplex[i]); evals += 1

    best = min(range(len(simplex)), key=lambda i: fv[i])
    return simplex[best], fv[best]


def cmaes(f, x0, sigma, max_evals, lo, hi, seed, log=None):
    """CMA-ES via the `cma` package. Returns (best_x, best_f).

    Preferred over Nelder-Mead when available: knots interact (a window is a
    shape, not a set of independent numbers), and the learned covariance
    exploits that, while box bounds keep candidates in the range that means
    anything. Seeded, so a rerun repeats the same search exactly.
    """
    import cma
    es = cma.CMAEvolutionStrategy(list(x0), sigma, {
        "bounds": [lo, hi],
        "maxfevals": max_evals,
        "seed": seed,
        "verbose": -9,
    })
    while not es.stop():
        xs = es.ask()
        es.tell(xs, [f(x) for x in xs])
        if log:
            log("  gen %3d: %d evals, best %d bytes"
                % (es.countiter, es.countevals, int(es.best.f)))
    return list(es.best.x), es.best.f


# ----------------------------------------------------------------------------
# Driver
# ----------------------------------------------------------------------------

DEFAULT_BASELINE = ["tukey050", "hann", "welch", "rect"]


def collect(paths):
    """Expand file/directory arguments into a sorted list of .flac files."""
    out = []
    for p in paths:
        if os.path.isdir(p):
            for root, _, files in os.walk(p):
                out += [os.path.join(root, f) for f in files if f.endswith(".flac")]
        else:
            out.append(p)
    missing = [p for p in out if not os.path.exists(p)]
    if missing:
        raise SystemExit("no such file: " + ", ".join(missing))
    return sorted(out)


def main():
    ap = argparse.ArgumentParser(
        description="Search for a window shape that shrinks real encoded output.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    ap.add_argument("--binary", default="build/flacoutcpp")
    ap.add_argument("--train", nargs="+", required=True,
                    help="corpus the search optimises against (files or dirs)")
    ap.add_argument("--validate", nargs="+", default=[],
                    help="held-out corpus, scored once at the end; the number "
                         "that actually counts")
    ap.add_argument("--mode", default="",
                    help="extra encoder flags, e.g. '-c 0' or '-e -c 8'")
    ap.add_argument("--objective", choices=["marginal", "standalone"],
                    default="marginal",
                    help="marginal: candidate is offered alongside --baseline; "
                         "standalone: candidate is the only window")
    ap.add_argument("--baseline", default=",".join(DEFAULT_BASELINE),
                    help="comma-separated window set the candidate joins/replaces")
    ap.add_argument("--knots", type=int, default=9)
    ap.add_argument("--seed", default="tukey050",
                    help="named shape or a knot file to start from")
    ap.add_argument("--optimizer", choices=["auto", "cmaes", "nelder-mead"],
                    default="auto",
                    help="auto uses cmaes when the `cma` package is installed")
    ap.add_argument("--seed-rng", type=int, default=1,
                    help="CMA-ES seed; only changes which search path is taken")
    ap.add_argument("--restarts", type=int, default=1,
                    help="extra runs from perturbed seeds")
    ap.add_argument("--max-evals", type=int, default=150, help="per restart")
    ap.add_argument("--step", type=float, default=0.15,
                    help="initial simplex edge, in knot units")
    ap.add_argument("--tol", type=float, default=1e-3,
                    help="stop when the simplex is smaller than this")
    ap.add_argument("--allow-negative", action="store_true",
                    help="let knots go to -1 (most windows are non-negative)")
    ap.add_argument("--pin-ends", action="store_true",
                    help="hold the first and last knot at 0 and search the rest")
    ap.add_argument("--out", default="", help="write the winning knot file here")
    args = ap.parse_args()

    if not os.path.exists(args.binary):
        raise SystemExit("no encoder at %s (build it first)" % args.binary)

    train = collect(args.train)
    validate = collect(args.validate) if args.validate else []
    baseline = [w for w in args.baseline.split(",") if w]
    mode = args.mode.split()
    lo = -1.0 if args.allow_negative else 0.0

    if os.path.exists(args.seed):
        vals = []
        for line in open(args.seed):
            line = line.split("#")[0].replace(",", " ").replace(";", " ")
            vals += [float(t) for t in line.split()]
        x_full = vals
        print("seed: %s (%d knots)" % (args.seed, len(x_full)))
    else:
        x_full = seed_knots(args.seed, args.knots)
        print("seed: %s sampled at %d knots" % (args.seed, args.knots))

    # With --pin-ends the optimiser only sees the interior knots; the fixed
    # zero endpoints are re-attached before every evaluation.
    def expand(x):
        return [0.0] + list(x) + [0.0] if args.pin_ends else list(x)

    x0 = x_full[1:-1] if args.pin_ends else x_full

    tmpdir = tempfile.mkdtemp(prefix="winsearch.")
    enc = Encoder(args.binary, mode)
    try:
        print("train:    %d file(s), %.1f MB"
              % (len(train), sum(os.path.getsize(f) for f in train) / 1e6))
        if validate:
            print("validate: %d file(s), %.1f MB"
                  % (len(validate), sum(os.path.getsize(f) for f in validate) / 1e6))
        print("objective: %s vs baseline [%s]%s"
              % (args.objective, ",".join(baseline),
                 (" with flags " + " ".join(mode)) if mode else ""))

        base_train = enc.size(train, baseline, tmpdir)
        print("\nbaseline train bytes: %d" % base_train)

        obj = Objective(enc, train, baseline, args.objective == "marginal",
                        lo, 1.0, tmpdir)

        def f(x):
            return obj(expand(x))

        seed_val = f(x0)
        print("seed     train bytes: %d  (%+d vs baseline)"
              % (seed_val, seed_val - base_train))

        use_cmaes = args.optimizer == "cmaes"
        if args.optimizer == "auto":
            try:
                import cma  # noqa: F401
                use_cmaes = True
            except ImportError:
                use_cmaes = False
        print("optimizer: %s" % ("CMA-ES" if use_cmaes else "Nelder-Mead"))

        for r in range(args.restarts + 1):
            if r > 0:
                # Perturb deterministically rather than randomly: a rerun of
                # this command must reproduce the same search.
                x_start = [x0[i] + args.step * math.sin(3.0 * (r + 1) * (i + 1))
                           for i in range(len(x0))]
                print("\nrestart %d" % r)
            else:
                x_start = list(x0)
                print("\nrun 0")
            if use_cmaes:
                x_start = [min(1.0, max(lo, v)) for v in x_start]
                xb, fb = cmaes(f, x_start, args.step, args.max_evals,
                               lo, 1.0, args.seed_rng + r, log=print)
            else:
                xb, fb = nelder_mead(f, x_start, args.step, args.max_evals,
                                     args.tol, log=print)
            print("  best this run: %d bytes (%+d vs baseline)"
                  % (fb, fb - base_train))

        best_val, best_knots = obj.best
        print("\n=== best on train ===")
        print("bytes:  %d  (%+d vs baseline, %+.4f%%)"
              % (best_val, best_val - base_train,
                 100.0 * (best_val - base_train) / base_train))
        shape = [min(1.0, max(lo, v)) for v in expand(best_knots)]
        peak = max(abs(v) for v in shape) or 1.0
        print("knots:  " + " ".join("%.4f" % (v / peak) for v in shape))
        print("evals:  %d encoder runs" % enc.runs)

        best_path = os.path.join(tmpdir, "best.txt")
        if args.out:
            shutil.copy(best_path, args.out)
            print("wrote:  %s" % args.out)

        if validate:
            print("\n=== held out ===")
            base_val = enc.size(validate, baseline, tmpdir)
            cand_val = enc.size(validate, obj.windows_for(best_path), tmpdir)
            delta = cand_val - base_val
            print("baseline: %d" % base_val)
            print("learned:  %d  (%+d, %+.4f%%)"
                  % (cand_val, delta, 100.0 * delta / base_val))
            train_gain = best_val - base_train
            if delta >= 0 and train_gain < 0:
                print("\nVERDICT: overfit — the shape helps only the training "
                      "audio. Not a window worth keeping.")
            elif delta < 0:
                print("\nVERDICT: holds up on unseen audio (%+.4f%% there vs "
                      "%+.4f%% on train)."
                      % (100.0 * delta / base_val,
                         100.0 * train_gain / base_train))
            else:
                print("\nVERDICT: no gain anywhere.")
    finally:
        if not args.out:
            print("\n(knot files left in %s)" % tmpdir)
        else:
            shutil.rmtree(tmpdir, ignore_errors=True)


if __name__ == "__main__":
    sys.exit(main())
