# Turn a .spv into a C header holding a uint32_t array. Run at build time by
# the FLACOUT_VULKAN branch of CMakeLists.txt; SPV and HDR come in via -D.
file(READ "${SPV}" _hex HEX)
string(LENGTH "${_hex}" _len)
math(EXPR _words "${_len} / 8")
set(_out "// Generated from shaders/sweep.comp -- do not edit.\n#pragma once\n#include <cstdint>\n\nstatic const uint32_t kSweepSpv[] = {\n")
set(_i 0)
while(_i LESS _words)
    math(EXPR _off "${_i} * 8")
    string(SUBSTRING "${_hex}" ${_off} 8 _w)
    # SPIR-V is little-endian on disk; reassemble each word byte-reversed.
    string(SUBSTRING "${_w}" 0 2 _b0)
    string(SUBSTRING "${_w}" 2 2 _b1)
    string(SUBSTRING "${_w}" 4 2 _b2)
    string(SUBSTRING "${_w}" 6 2 _b3)
    string(APPEND _out "0x${_b3}${_b2}${_b1}${_b0},")
    math(EXPR _nl "(${_i} + 1) % 8")
    if(_nl EQUAL 0)
        string(APPEND _out "\n")
    else()
        string(APPEND _out " ")
    endif()
    math(EXPR _i "${_i} + 1")
endwhile()
string(APPEND _out "\n};\n")
file(WRITE "${HDR}" "${_out}")
